# Generated by Django 3.2.7 on 2021-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_salary', models.IntegerField()),
                ('emp_email', models.CharField(max_length=30)),
            ],
        ),
    ]
